Firefox MV3
LiveTL/HyperChat pull request #115
Opened 2023-03-12 22:16 UTC by r2dev2

Adds support for MV3 in Firefox. Some things to note:

## Problems
1. ff does not support service workers in their mv3 "support"
2. ff does not support extension to content script channels in their mv3 "support"

## Solutions
1. use bg script for ff and service workers for chrome
	* implies that chrome and ff need completely different manifests (one is not superset of other)
	* introduce `yarn dev:firefox` and `yarn dev:chrome` and make `yarn start` alias for `yarn dev:chrome`
2. proxy extension to content script messages through background script for ff
	* unsure how long bg script for ff persists, I _think_ it should stay up as long as chat is active?
	* should give to ff beta testers to make sure it actually works over long intervals

2023-03-12 22:20 UTC, KentoNishi requested changes
can you swap `yarn build` to be chrome by default and add a `yarn build:firefox` instead?

2023-03-12 22:43 UTC, r2dev2 commented
> can you swap `yarn build` to be chrome by default and add a `yarn build:firefox` instead?

Done in aa99119

2023-03-13 00:06 UTC, KentoNishi requested changes
u forgot to update the readme

2023-03-13 18:35 UTC, r2dev2 commented
> u forgot to update the readme

[a7eccb8](https://github.com/LiveTL/HyperChat/pull/115/commits/a7eccb8bf4643334409442e6b84e5c4f01c3e75f)

2023-03-13 19:19 UTC, KentoNishi approved these changes

2023-03-21 22:15 UTC, merged