Performance tweaks
LiveTL/HyperChat pull request #26
Opened 2021-11-29 13:09 UTC by ChrRubin

Various tweaks that should help with HyperChat performance, especially with slower hardware:

- Queued messages from the YTC JSON parser are sent in 250ms batches, instead of on each individual message. Reduces the frequency of svelte array updates.
This is a breaking change in the background messaging API that will require an update on LTL side (LiveTL/LiveTL@9893b3c).
- Chat history size is reduced from 250 to 150. Nobody needs to scroll that much anyway. 150 is based on Twitch chat.
- Message truncation is changed from running on a timer to being based on chat history size. Truncation is only done if the amount of messages is 20 larger than chat history size, which will then be spliced down to the chat history size. Helps spread DOM operations into smaller chunks during heavy chat traffic.

From my testing on an Intel Atom x5-Z8350 tablet PC, these tweaks saw a pretty consistent 5-15% lower CPU usage compared to v2.0.1 on chat-heavy streams (such as HoloX debut streams), which is honestly pretty good considering how shit this PC is. Performance during slow chats is basically similar with before, and of course these changes barely make a difference on modern hardware.

As a side note, I also tested using a variation of the double rotating array Kento used in Vue HC (2297dd3), and plain array splicing still performed better, not to mention being much, much simpler code-wise.

Also another fun fact, HyperChat v1.3.4 actually performs *WORSE* than YTC during Chloe's debut, at least on this shitty PC. Good thing we jumped off that ship already lol.

2021-12-20 04:40 UTC, ChrRubin commented
Bump

2022-01-10 23:49 UTC, KentoNishi approved these changes

2022-01-11 01:10 UTC, r2dev2 requested changes

2022-01-11 23:06 UTC, r2dev2 approved these changes

2022-01-12 00:28 UTC, merged