Fixed parsing missing authorName
LiveTL/HyperChat pull request #28
Opened 2021-12-01 23:46 UTC by lbmaian

Fixed parsing missing authorName (yes, this is apparently possible) 

Also console.error failed parse actions (used to identify this bug)

2021-12-02 09:56 UTC, ChrRubin requested changes
Can you update `ytc.d.ts` to reflect that `authorName` is optional?

2021-12-02 12:10 UTC, lbmaian commented
> Can you update `ytc.d.ts` to reflect that `authorName` is optional?

Done

2021-12-02 13:14 UTC, ChrRubin approved these changes

2021-12-03 04:18 UTC, lbmaian commented
Heya is anything blocking the merge from happening?

2021-12-03 06:17 UTC, merged