Options/Settings page
LiveTL/HyperChat pull request #39
Opened 2022-01-18 16:25 UTC by ChrRubin

Implements a simple settings page for HyperChat. Currently includes options for theme and to show/hide profile icons, timestamps, usernames and user badges.

## Screenshots
| Light theme | Dark theme |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20059164/149976135-c62d27f7-ccb6-4dea-b808-db5cbf180d89.png) | ![image](https://user-images.githubusercontent.com/20059164/149976208-8e83dcc1-174a-4a62-b84e-777e7c90ea37.png) |
| ![image](https://user-images.githubusercontent.com/20059164/149976345-db407f0b-3697-42d2-9201-d5bb0221d95f.png) |  ![image](https://user-images.githubusercontent.com/20059164/149976415-e4e4b866-359c-4cb9-b51d-cb4f46a2642b.png) |

| All enabled | All disabled |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20059164/149976774-287a92e3-9b36-442b-a580-65836b84e23a.png) |  ![image](https://user-images.githubusercontent.com/20059164/149976818-eb228ce9-6b4f-415d-9790-2827e710d7b8.png) |

Closes #6, closes #14, closes #18, closes #24.

2022-01-20 20:30 UTC, KentoNishi commented
![image](https://user-images.githubusercontent.com/38841491/150417234-ee900af2-98b9-474e-b16a-faf9c068888c.png)

2022-01-21 05:50 UTC, KentoNishi approved these changes

2022-01-22 21:51 UTC, r2dev2 requested changes
This doesn't work on Firefox after the second update to the settings.

https://user-images.githubusercontent.com/50760816/150656586-003ac4a6-0436-43b3-a001-f81fd3c4d6e0.mp4

2022-01-22 21:51 UTC, r2dev2 commented on src/components/Hyperchat.svelte
> +  );
You could just do
```js
$: $store1, $store2, scrollToBottom();
```

2022-01-22 21:51 UTC, r2dev2 commented on src/ts/chat-constants.ts
> +export const getBrowser = (): Browser => {
instead of removing the constant, you should just extract the `getBrowser` function and then `export const BROWSER = getBrowser()`.

2022-01-22 21:54 UTC, KentoNishi commented on src/components/Hyperchat.svelte
> +  );
this is both the dumbest and most gigabrain line of code ive ever seen

2022-01-22 22:44 UTC, r2dev2 commented
@ChrRubin I made a pr to fix the infinite loop.

2022-01-23 04:06 UTC, ChrRubin commented on src/components/Hyperchat.svelte
> +  );
Yeah but eslint hates it lol

2022-01-23 04:35 UTC, ChrRubin commented on src/ts/chat-constants.ts
> +export const getBrowser = (): Browser => {
Oh yeah I did this as kind of a test for webpack tree shaking. So apparently constants that call a function gets imported no matter what when anything from the module is imported. Here's an example from `options.bundle.js` where browser detection isn't used.

Exporting as constant (including `export const BROWSER = getBrowser()`):
![image](https://user-images.githubusercontent.com/20059164/150664750-999d8885-077c-49a8-b7c5-55a9bc53314b.png)

Just exporting as a function:
![image](https://user-images.githubusercontent.com/20059164/150664805-3b783532-c98c-4a6c-95ab-a4c5538c3a38.png)

As you can see the unused code still gets bundled when just using the variable. There's even the unused URLSearchParams stuff here.

2022-01-23 04:48 UTC, ChrRubin commented on src/ts/chat-constants.ts
> +export const getBrowser = (): Browser => {
What I've learnt from this is that for ideal tree shaking, instead of using a single file for all constants, it should be separated into multiple related files, like one for browser detection and one for URLSearchParams etc.

Of course this might only apply for webpack. I'm waiting for this to be merged so I can test this out on vite.

2022-01-23 06:46 UTC, r2dev2 commented on src/ts/chat-constants.ts
> +export const getBrowser = (): Browser => {
I'm not sure why but I get that webpack tree-shakes when a constant is used?

I added the following to constants and when I ran `yarn build:production`, `this is a test` was not found in `build/chat-injector.ts`.

![bru moment](https://user-images.githubusercontent.com/50760816/150667730-5bcccba2-6f78-4bb7-b76e-c3ef0a30be24.png)

Just to be safe, I suppose you *could* add `'use strict';` to the top of the module which would declare it pure and free of side effects which would make tree-shaking that function fair game for webpack.

2022-01-23 06:55 UTC, r2dev2 commented on src/components/Hyperchat.svelte
> +  );
You could disable the warning as the `,` separated statements is the recommended way to do it according to r/svelte, but a part of me wants this gigabrain workaround in the codebase lmao.

2022-01-23 06:55 UTC, r2dev2 approved these changes
It works well

2022-01-23 06:56 UTC, KentoNishi approved these changes

2022-01-23 07:01 UTC, ChrRubin commented on src/ts/chat-constants.ts
> +export const getBrowser = (): Browser => {
It still bundles the function, albeit a stripped version of it for whatever reason:
![image](https://user-images.githubusercontent.com/20059164/150668086-d071b067-eb8d-48d4-b269-dea6950861bd.png)

`'use strict';` does nothing for tree shaking, same with `"sideEffects": false`, although the latter is more for libraries' package.json so webpack can do its thing for those.

2022-01-23 07:03 UTC, merged