tl regions fix
LiveTL/HyperChat pull request #55
Opened 2022-02-24 20:55 UTC by KentoNishi

fixes https://github.com/LiveTL/HyperChat/issues/52 and other related issues.

2022-03-14 14:07 UTC, ChrRubin commented
Switching to draft since this hasn't been fixed.

2022-03-20 05:26 UTC, KentoNishi commented
![image](https://user-images.githubusercontent.com/38841491/159149485-b7ae1561-250f-4a5c-9199-333acb8033a7.png)

confirmed to work pog

2022-03-20 06:00 UTC, r2dev2 requested changes
It works with my computer, just some types to clean up.

2022-03-20 06:17 UTC, KentoNishi commented
![image](https://user-images.githubusercontent.com/38841491/159150696-051acf24-21a9-44cd-ae7c-b796b0d74983.png)

2022-03-20 06:37 UTC, r2dev2 requested changes

2022-03-20 06:37 UTC, r2dev2 commented on src/components/settings/MessageTranslationSettings.svelte
> +  const priority: (AvailableLanguageCodes)[] = [
Remove parenthesis around `AvailableLanguageCodes`

2022-03-20 06:37 UTC, r2dev2 commented on src/components/settings/MessageTranslationSettings.svelte
> +    ...(Object.keys(AvailableLanguages) as (AvailableLanguageCodes)[])
Remove parenthesis around `AvailableLanguageCodes`

2022-03-20 06:40 UTC, r2dev2 commented on src/components/settings/MessageTranslationSettings.svelte
> +    ...(Object.keys(AvailableLanguages) as (AvailableLanguageCodes)[])
Ok nvm my gh got confused parens are gone.

2022-03-20 06:41 UTC, r2dev2 commented on src/components/settings/MessageTranslationSettings.svelte
> +  const priority: (AvailableLanguageCodes)[] = [
Nvm my gh glitched parens are actually gone.

2022-03-20 06:41 UTC, r2dev2 approved these changes

2022-03-21 02:34 UTC, ChrRubin requested changes

2022-03-21 02:34 UTC, ChrRubin commented on src/components/settings/MessageTranslationSettings.svelte
> +  ];
Is reactive needed here?

2022-03-21 02:34 UTC, ChrRubin commented on src/ts/storage.ts
> +  });
I mean you could've just chained `.catch(console.error)` instead of disabling the floating promises checks.

Also on line 33 you can use `translateTargetLanguage.getCurrent()`, since you already awaited `ready` and the value should be populated without needing to read from store again. The svelte `get` function also goes thru the whole subscribe unsubscribe process.

2022-03-21 03:29 UTC, KentoNishi commented on src/ts/storage.ts
> +  });
dont want it to have extra console logs, id rather disable the error

2022-03-21 03:30 UTC, KentoNishi commented on src/ts/storage.ts
> +  });
fck it i'll do it anyway

2022-03-21 03:54 UTC, ChrRubin approved these changes

2022-03-21 03:57 UTC, merged