Add option to auto switch to Live Chat
LiveTL/HyperChat pull request #60
Opened 2022-03-14 13:57 UTC by ChrRubin

Adds an option to automatically switch chat mode to Live Chat when enabled.

2022-03-18 14:49 UTC, r2dev2 requested changes
The prompt should be in the same style as LiveTL's auto-launch prompt
![livetl's auto launch prompt](https://user-images.githubusercontent.com/50760816/159025247-0e21b0c5-1a48-4689-95f3-3c377f403ca5.png)

Maybe `Default Chat` would be a better prompt?

2022-03-18 14:49 UTC, r2dev2 commented on src/components/settings/InterfaceSettings.svelte
> +  <Checkbox name="Automatically switch to Live Chat" store={autoLiveChat} />
![auto-switch to livechat checkbox](https://user-images.githubusercontent.com/50760816/159023811-a9504b37-5802-43e2-adef-1a7944000192.png)

When I first saw this, it kinda looked like the option also pertained to the Theme setting because it is right under a label with `:` at the end. Perhaps this should be a radio store of `Automatically switch to: Top Chat, Live Chat` as now that we can switch the default on a whim, the default behavior of YouTube's chat doesn't matter as much.

2022-03-20 04:48 UTC, KentoNishi commented on src/components/settings/InterfaceSettings.svelte
> +  <Checkbox name="Automatically switch to Live Chat" store={autoLiveChat} />
i'll work on the UI side of things

2022-03-21 03:33 UTC, KentoNishi commented
aight imma work on this now

2022-03-21 03:54 UTC, KentoNishi commented
![image](https://user-images.githubusercontent.com/38841491/159202746-3a0f7017-fe0e-41f4-a459-b0750fe04939.png)
![image](https://user-images.githubusercontent.com/38841491/159202772-60e058f2-58c9-4c4d-bcc0-e570d6cfb4ba.png)

2022-03-21 03:56 UTC, ChrRubin commented
That works too (I can't review my own PR).

2022-03-21 03:57 UTC, KentoNishi approved these changes

2022-03-21 03:57 UTC, KentoNishi commented
i'll merge locally

2022-03-21 03:58 UTC, r2dev2 approved these changes

2022-03-21 04:04 UTC, merged