make system emojis optional (off by default)
LiveTL/HyperChat pull request #62
Opened 2022-03-21 17:23 UTC by KentoNishi

![image](https://user-images.githubusercontent.com/38841491/159329220-16bb4b94-70a8-46ab-95a9-b8b65d6dc6a1.png)

![image](https://user-images.githubusercontent.com/38841491/159329227-f8393563-c144-47d3-93c8-1b0d374c7118.png)

2022-03-26 04:44 UTC, r2dev2 approved these changes

2022-03-26 04:44 UTC, r2dev2 commented on src/components/settings/MessageTranslationSettings.svelte
> +    <DropdownStore name="Target language"
We need to fix the formatter config lmao.

@KentoNishi plskudasai can u import ur good config into hc.

2022-03-27 09:39 UTC, ChrRubin requested changes

2022-03-27 09:39 UTC, ChrRubin commented on .eslintrc.js
> +    'no-unused-expressions': 'off',
These should be at L34 so they're only applied to svelte files.

2022-03-28 07:38 UTC, ChrRubin approved these changes

2022-03-28 07:51 UTC, merged