reduced chat delay
LiveTL/HyperChat pull request #63
Opened 2022-03-21 19:13 UTC by KentoNishi

I figured out a trick to make the delay negligible.

When a chunk is received and is completely sorted, we assume that the first message in the chunk is meant to be displayed immediately. All messages that follow are timed relative to the first message. I think this is what ytc does internally, since the timing is very very close to default ytc. So much so that screenshots in chilledcow chat show an identical list of messages

left hc, right ytc.

![image](https://user-images.githubusercontent.com/38841491/159346715-7aedceef-ab78-44e4-bd1f-10a785468023.png)

2022-03-21 19:28 UTC, KentoNishi commented
converting pr to draft cuz i realized i might have to change things for replay chat

2022-03-21 21:10 UTC, KentoNishi commented
![image](https://user-images.githubusercontent.com/38841491/159364334-66967d38-0fd0-43c6-824f-0c0d60d0b1a5.png)

this is pog

2022-03-27 09:32 UTC, ChrRubin requested changes
Sometimes the easiest solution is the best solution lmao

2022-03-27 09:32 UTC, ChrRubin commented on src/ts/chat-parser.ts
> +};
Can calculate the diff before forEach so `Date.now()` won't get called for each message.

2022-03-28 07:38 UTC, ChrRubin approved these changes

2022-03-28 07:53 UTC, merged