instant fake message sending
LiveTL/HyperChat pull request #65
Opened 2022-03-25 02:13 UTC by KentoNishi

the slight delay is because we still have to wait for youtube to respond to the message send request to evaluate how it should be rendered, while youtube locally computes it themselves. the delay is way less than before now, though.

https://user-images.githubusercontent.com/38841491/160041018-c13a87ac-08da-4035-883f-ad55ebfe4d33.mp4

implements #9

2022-03-25 07:07 UTC, KentoNishi commented
i may have identified an even faster way to do this, ig review the other prs first

2022-03-25 18:17 UTC, KentoNishi commented
sub-second delay now

2022-03-26 06:06 UTC, r2dev2 requested changes
It works though.

2022-03-26 06:06 UTC, r2dev2 commented on src/ts/queue.ts
> +          forceDisplay || m.author.id !== selfChannel.get()?.authorExternalChannelId
Extract each side of the and into a variable so it communicates what the and is checking for clearly. Also, the `setInitial` in the beginning of the second part of the first or is not needed because `!setInitial` is checked for already.

2022-03-26 07:06 UTC, r2dev2 approved these changes

2022-03-27 10:11 UTC, ChrRubin requested changes

2022-03-27 10:11 UTC, ChrRubin commented on src/ts/queue.ts
> +  addActionChunk: (chunk: Ytc.ParsedChunk, setInitial?: boolean, forceDisplay?: boolean) => void;
`addActionChunk` isn't used outside of YtcQueue, so I don't think we need to expose it.

2022-03-27 17:51 UTC, KentoNishi commented on src/ts/queue.ts
> +  let selfChannel = subscribable<Ytc.TextMessageRenderer | null>();
it doesn't work because when setting the value via `queue.selfChannel = value;`, it replaces the entire variable. so `queue.selfChannel` will have the correct value while the `selfChannel` variable will remain unchanged. I realize that we can switch to using a const subscribable tho, i'll do that

2022-03-28 07:38 UTC, ChrRubin approved these changes

2022-03-28 07:51 UTC, merged