ban and report (wip)
LiveTL/HyperChat pull request #71
Opened 2022-04-22 23:24 UTC by KentoNishi

2022-05-11 04:37 UTC, KentoNishi commented
https://user-images.githubusercontent.com/38841491/167770103-c7d855be-5f5a-4c40-8d27-5d93693a6a83.mp4

2022-05-11 04:38 UTC, KentoNishi commented
@r2dev2 @ChrRubin ***DO NOT USE THE REPORT FEATURE ON ARBITRARY COMMENTS!*** YT bans people who submit a bunch of false reports.

2022-05-11 23:08 UTC, r2dev2 requested changes
Blocking works in chrome, but not in firefox. In firefox, it errs out and the following is logged to the console:

![firefox blocking](https://user-images.githubusercontent.com/50760816/167961740-35382ba0-ea65-402a-860a-04e5991615d4.png)

2022-05-11 23:32 UTC, KentoNishi commented
i think i know what the issue is. fck

2022-05-13 01:28 UTC, r2dev2 approved these changes
Both blocking and reporting work on my end.

2022-05-18 10:42 UTC, ChrRubin requested changes
The menu should be hidden when user is not logged in. Both of the options will error when not logged in.

![image](https://user-images.githubusercontent.com/20059164/169017843-b637d1e4-0a51-492c-9439-f8455fbcb078.png)

![image](https://user-images.githubusercontent.com/20059164/169020883-b6f7e938-2315-4411-be65-f9b9bdf4620d.png)

![image](https://user-images.githubusercontent.com/20059164/169020918-9917dbae-e507-4210-a4c8-1188343504b1.png)

2022-05-18 10:42 UTC, ChrRubin commented on src/scripts/chat-interceptor.ts
> +    console.log(response);
We keeping this?

2022-05-18 10:42 UTC, ChrRubin commented on src/scripts/chat-background.ts
> +  const user = actionPanel.liveChatRestrictedParticipationRenderer
actionPanel can be undefined.

![image](https://user-images.githubusercontent.com/20059164/169020146-f3612ba3-dbbb-4163-8151-54335682ccb4.png)

2022-05-19 03:53 UTC, ChrRubin approved these changes

2022-05-19 04:24 UTC, KentoNishi commented
Let's fckn gooooooo

2022-05-19 04:24 UTC, merged