fix: text overflow on header bar if button text too long
LiveTL/HyperChat pull request #72
Opened 2022-04-25 13:02 UTC by 404-Program-not-found

added code that injects CSS into the page upon hyperchat activation. This fixes the issue described in error #53

2022-04-25 13:52 UTC, ChrRubin requested changes

2022-04-25 13:54 UTC, 404-Program-not-found commented on src/scripts/chat-injector.ts
> +
Got it, will change in a few mins

2022-04-26 06:51 UTC, ChrRubin approved these changes

2022-04-26 17:54 UTC, KentoNishi approved these changes
looks good

2022-04-26 17:54 UTC, merged