Add support for persistent superchats
LiveTL/HyperChat pull request #79
Opened 2022-05-30 06:34 UTC by KentoNishi

Implements https://github.com/LiveTL/HyperChat/issues/49

![image](https://user-images.githubusercontent.com/38841491/170931124-636eb195-194c-4f54-b543-fade7822ad78.png)
![image](https://user-images.githubusercontent.com/38841491/170931114-a0defcc1-cde0-4611-b6a6-217ee85cc3e5.png)

2022-05-31 05:03 UTC, r2dev2 requested changes
The superchat bar is in light theme when yt is in dark theme when "use yt theme" is selected. I just did `yarn start:firefox` for this. The theme of the superchat bar works fine for manually set themes however. Everything else seems to be fine.

![superchat bar in light theme with yt in dark theme](https://user-images.githubusercontent.com/50760816/171096319-0d2cbb23-c279-471b-91b7-39a117319eba.png)

2022-05-31 20:28 UTC, r2dev2 approved these changes

2022-06-06 11:48 UTC, ChrRubin requested changes
Some extra stuff aside from the comments:

- The ticker bar seems to just disappear randomly and never come back? I experienced this during Watame's BDay live on both Firefox and Chromium. Seems to only affect live streams and not VODs. No errors in the console.

- If we want to use name for the ticker items instead of profile pic like YTC does, we might want to truncate it in case of people with long names taking up too much space like this one:

![image](https://user-images.githubusercontent.com/20059164/172154224-0b06af35-e061-4f3d-a9ff-394b7c6deb17.png)

- Membership items (not talking about gifts) and membership milestone chats aren't being stickied even though they are on normal YTC. 

- Adding a setting to toggle the ticker bar would be nice.

2022-06-06 11:48 UTC, ChrRubin commented on src/components/Settings.svelte
> +    scrollbar-color: #888 transparent;
`webkit-scrollbar-track` probably isn't needed if thin scrollbars are removed. Also if we're removing thin scrollbars here on Chrome, we should also remove it on Firefox.

2022-06-06 11:48 UTC, ChrRubin commented on src/components/SuperchatViewDialog.svelte
> +  </div>
The close button feels unnecessary.

2022-06-06 12:07 UTC, ChrRubin commented
Ran with Astel's BDay live and now the ticker bar is always there but new superchats aren't added to it lmao

2022-06-06 19:21 UTC, KentoNishi commented
> Membership items (not talking about gifts) and membership milestone chats aren't being stickied even though they are on normal YTC.

this is intentional, imo they dont belong in the superchat bar and it just gets in the way of actual messages that need to be stickied so imma leave that as it is

2022-06-06 19:22 UTC, KentoNishi commented
altho ig there are membership joins with messages, we could add that later possibly

2022-06-11 03:58 UTC, KentoNishi commented
@ChrRubin it took a while, but i implemented all the suggestions and improved stuff all around. pls review thx

2022-06-11 03:58 UTC, KentoNishi commented
![image](https://user-images.githubusercontent.com/38841491/173171672-f6aacfc1-817e-44e0-aecd-1d51f90b0751.png)

2022-06-11 04:13 UTC, KentoNishi commented
hmmmmmm odd, the issue of new ticker items not being added in livestreams still happens...

2022-06-11 05:27 UTC, KentoNishi commented
ok fixed it, the issue was that the superchat was added but was getting deleted immediately because the poll time wasn't caught up. pls try now @ChrRubin

2022-06-13 12:04 UTC, ChrRubin requested changes
Aside from the absolute div, seems good

2022-06-13 19:17 UTC, KentoNishi commented on src/components/Hyperchat.svelte
> +  </div>
this is the same with pinned messages btw.

2022-06-14 08:53 UTC, KentoNishi commented
@ChrRubin 

https://user-images.githubusercontent.com/38841491/173536345-52f054e6-3356-45ea-9334-8fcc6fb14383.mp4

2022-06-16 10:21 UTC, ChrRubin commented
LMAO I assumed you were gonna just put the sticky bar as a separate div above the "main" HC div like how YTC does it.

Could you try to do that instead, or is there some other problem preventing that? Seems to me like it'll involve a lot less fucking around with the heights and stuff and will fix this OCD trigger:

https://user-images.githubusercontent.com/20059164/174049354-b1124563-5095-44b5-ab5a-4b8b371b279b.mp4

2022-06-16 11:31 UTC, ChrRubin commented on src/scripts/chat-background.ts
>      }, () => {});
We sure we wanna remove the width/height? The defaults seems a tad large.

![image](https://user-images.githubusercontent.com/20059164/174060393-da5c4f1a-366f-4d55-b8ec-9aa9e2ec4721.png)

2022-06-16 11:45 UTC, ChrRubin commented
I've fixed the OCD trigger in ba7bc8d, so the sticky bar is no longer in an absolute div. Pinned messages not blocking the top few messages is nice so we should still keep that part regardless.

For the popup, I think we should still specify a certain size instead of letting the browser wing it and fill up half of the screen. Maybe slightly larger than before if needed.

2022-06-16 19:58 UTC, KentoNishi commented
@ChrRubin chrome now inconsistently enforces a minimum pop-up window area size based on the percentage of area it occupies. I realized this while deving on my laptop -- chrome throws an error if a window takes less than 50% of available screen area, blocking the pop-up. Getting rid of the dimensions is the easiest solution, unless u wanna try messing with measuring screen dimensions and sht lol

2022-06-16 20:04 UTC, KentoNishi commented
btw @ChrRubin here's the error, screenshotted from the production chrome listing

![image](https://user-images.githubusercontent.com/38841491/174154689-48168e01-9519-420e-aaf3-92bf1f6dad3e.png)

2022-06-17 05:49 UTC, ChrRubin commented
> btw @ChrRubin here's the error, screenshotted from the production chrome listing
> 
> ![image](https://user-images.githubusercontent.com/38841491/174154689-48168e01-9519-420e-aaf3-92bf1f6dad3e.png)
> 

Jesus that's stupid. No wonder the default literally just fills up half of the screen on Chrome.

2022-06-17 05:50 UTC, ChrRubin approved these changes
@KentoNishi you should double-check that my commit doesn't mess up any of the stuff you changed. Seems good to me at quick glance

2022-06-17 06:10 UTC, KentoNishi commented
Got it, will do after I get back to mah hotel

2022-06-17 06:58 UTC, merged