show chip if hc updates while it's disabled
LiveTL/HyperChat pull request #86
Opened 2022-06-25 06:36 UTC by KentoNishi

taishi didn't know that hyperchat had user reporting and blocking because he had hyperchat turned off and never saw the changelogs (outside of the minimized livetl changelogs). i think there are probably quite a few people who have hyperchat disabled most of the time because of something they dont like, not realizing that the feature has been implemented recently. this chip would help alert those users that there's new stuff they don't know about

![image](https://user-images.githubusercontent.com/38841491/175760742-b89c052a-9eca-4a29-aa2d-5e4008059247.png)

when hovered, the chip chevron turns into an `x`.

![image](https://user-images.githubusercontent.com/38841491/175761648-b91c0064-1efc-49cb-80dc-6d3addf85be5.png)
![image](https://user-images.githubusercontent.com/38841491/175761649-ad0c6b2b-3f29-4bdf-9976-8c0662ad02b8.png)

2022-06-26 03:41 UTC, ChrRubin requested changes

2022-06-26 03:41 UTC, ChrRubin commented on src/components/HyperchatButton.svelte
> +      }}>
Should change to a div so it doesn't behave like a normal link (address tooltip shown on bottom left of browser, right click shows link actions etc)

2022-06-26 03:41 UTC, ChrRubin commented on src/components/HyperchatButton.svelte
> +        </svg>
Does @mdi/js not have the icons or are they not behaving as expected?

2022-06-26 20:44 UTC, KentoNishi commented
i aint gonna lie, i forgot mdi existed

2022-07-01 06:21 UTC, r2dev2 approved these changes

2022-07-01 22:20 UTC, merged