Colored mentions
LiveTL/HyperChat pull request #92
Opened 2022-07-06 02:40 UTC by KentoNishi

the approach i took for this is (hopefully) more efficient than what youtube does, since it highlights the entire message rather than each instance of a ping. this also fixes an issue in youtube where pinging someone with an emoji in their name doesn't work.

![image](https://user-images.githubusercontent.com/38841491/177456029-ef3a0ad0-cc81-4dd8-8004-f5d55122ce36.png)

![image](https://user-images.githubusercontent.com/38841491/177456116-f2d02f49-5113-464f-8645-22739d1672bc.png)

2022-07-06 06:17 UTC, KentoNishi commented
![image](https://user-images.githubusercontent.com/38841491/177481979-80acad7d-f209-436b-a40b-139c4d336ebd.png)

2022-07-06 06:18 UTC, KentoNishi commented
![image](https://user-images.githubusercontent.com/38841491/177481979-80acad7d-f209-436b-a40b-139c4d336ebd.png)

now works on vods

2022-07-10 07:58 UTC, r2dev2 requested changes
Can you make a settings option to opt into enabling user highlighting?

2022-07-11 00:31 UTC, r2dev2 approved these changes

2022-07-11 00:32 UTC, KentoNishi commented
@ChrRubin review pls

2022-07-11 12:03 UTC, ChrRubin commented on src/scripts/chat-background.ts
> +      state: 'maximized'
Wait why are we maximizing popups? This will affect the LiveTL popup too.

2022-07-11 15:56 UTC, KentoNishi commented on src/scripts/chat-background.ts
> +      state: 'maximized'
I tested the pop-up window on multiple screen sizes, and for some reason it keeps opening a super vertically short window (maybe like 20px tall 400px wide). Idk maybe this is just a me problem, I guess I can just remove this part then

2022-07-11 16:26 UTC, ChrRubin approved these changes

2022-07-11 16:39 UTC, merged